apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}  
      sslmode: "disable"
      postgresVersion: 1500